import "~/styles/globals.css"

import { Inter } from "next/font/google"
import Link from "next/link"
import dynamic from "next/dynamic"

const Header = dynamic(() => import("~/components/Header").then((mod) => mod.Header), { ssr: false })

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-sans",
})

export const metadata = {
	title: "Create T2 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={`font-sans ${inter.variable}`}>
				{/* use layered top layout later like on v1 */}
				<Header />
		
				{children}

				{/* dont use futter at all like in v1 */}
				<footer className="flex h-16 w-full items-center justify-between bg-[#0a192f] px-4 py-2 text-white">
					<h2 className="text-2xl font-bold">foot V2</h2>
					<h2 className="text-2xl font-bold">foot V3</h2>
				</footer>
			</body>
		</html>
	)
}
